#!/usr/bin/env python

from .utils import EnumWithDescription as Enum


class ERRORS(Enum):
    """
    Códigos de error de la API

    Cada código de error tiene un mensaje asociado.
    """

    NO_ROS_CONNECTION = "NO_ROS_CONNECTION", "La conexión con ROS no está disponible."
    NO_AVAILABLE_IN_MODE = "NO_AVAILABLE_IN_MODE", "No disponible en el modo actual."
    MODE_NOT_READY = "MODE_NOT_READY", (
        "El modo solicitado aun se encuentra en proceso" "de inicialización."
    )
    NO_MAP_LOADED = "NO_MAP_LOADED", (
        "El mapa no se encuentra cargado en el robot, o"
        " se está solicitando en el modo incorrecto."
    )
    NO_MAP_DATA = "NO_MAP_DATA", (
        "El mapa se encuentra cargado en el robot pero no se" " encuentra disponible."
    )
    NO_BATTERY_DATA = "NO_BATTERY_DATA", "No hay dato de batería."

    # For mode change
    MAP_INVALID = "MAP_INVALID", "El mapa seleccionado no es válido."
    # For navigation mode:
    CURRENTLY_ON_PATH = "CURRENTLY_ON_PATH", "El robot se encuentra en un recorrido."

    # For CREATE request on (map, stop waypoints)

    # this errors is generated by serializer validation
    NAME_REQUIRED = "NAME_REQUIRED", "El nombre es requerido."
    NAME_UNIQUE = "NAME_UNIQUE", "El nombre ya se encuentra en uso."

    # For CREATE request on waypoint
    NO_POSE_AVAILABLE = "NO_POSE_AVAILABLE", "No hay dato de posición del robot."
    NO_MAP_EXISTS = "NO_MAP_EXISTS", "El robot no está publicando el mapa."

    # For CREATE request on path
    # this errors is generated by serializer validation
    MAP_REQUIRED = "MAP_REQUIRED", "El mapa es requerido."
    # this errors is generated by serializer validation
    STOP_WAYPOINTS_REQUIRED = "STOP_WAYPOINTS_REQUIRED", (
        "Se requiere un punto de" " parada."
    )
    # this errors is generated by serializer validation
    MAP_DOES_NOT_EXIST = "MAP_DOES_NOT_EXIST", "El mapa no existe."
    # this errors is generated by serializer validation
    WAYPOINT_DOES_NOT_EXIST = "WAYPOINT_DOES_NOT_EXIST", "El punto de parada no existe."
    WAYPOINTS_IN_SAME_MAP = "WAYPOINTS_IN_SAME_MAP", (
        "El punto de parada no pertenece al mapa."
    )

    NO_ROBOT_NAME = "NO_ROBOT_NAME", "No se ha encontrado el nombre del robot."

    NO_IMAGE_AVAILABLE = "NO_IMAGE_AVAILABLE", "No hay imagen disponible."

    OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND", "No se encontró el objeto."
    REF_OBJECT_NOT_FOUND = (
        "REF_OBJECT_NOT_FOUND",
        "No se encontró el objeto de referencia.",
    )
